### ISSUE TITLE
Cleanup Custom JSON Helpers

### ISSUE THREAD

**Issue by hawkerm** [hawkerm/monaco-editor-uwp#13]
Should look at if can remove dependency on JSON.NET for DataContractSerializer and remove all initial custom JSON helpers.

**Comment by hawkerm** [comment]
This is being done in #30 I believe.

**Comment by hez2010** [comment]
Currently `System.Text.Json` doesn't support UWP yet, removing JSON.NET may be postponed to a later release.

**Comment by hawkerm** [comment]
@hez2010 yup, I've been waiting for them to fix the UWP `System.Text.Json` issue, but I mean to refer to just the cleaning up the old manual helpers. Thanks for doing so many clean-up steps as part of your PR! :)

**Comment by hawkerm** [comment]
I'm going to close this issue and re-open a new one for the `System.Text.Json`.
