### ISSUE TITLE
Suggestions not showing

### ISSUE THREAD

**Issue by beraybentesen** [hawkerm/monaco-editor-uwp#20]
When pressing "." suggestions not showing (it shows when I start typing.

**Comment by hawkerm** [comment]
@beraybentesen I haven't exposed the intellisense configuration apis yet, but it's on my roadmap.  However, I think except for some basic JavaScript, you have to provide the specification to the Monaco engine.  Normally most of that is implemented through extensions to VS Code which pass it into Monaco, I believe.

What language are you looking at providing suggestions for?

**Comment by hawkerm** [comment]
I should be looking at exposing some of the events to C# in the next couple of weeks, but until then, if you're not afraid of JavaScript, you could inject your custom scenario into the [Monaco initialization](https://github.com/hawkerm/monaco-editor-uwp/blob/master/MonacoEditorComponent/MonacoEditor.html) for the control.

They have fairly good examples and docs on [their site](https://microsoft.github.io/monaco-editor/index.html) about how to use their API.

**Comment by hawkerm** [comment]
@beraybentesen, I added the CustomItem provider in 0.7, so this scenario should be available now.
