### ISSUE TITLE
Missing Method to SetPosition

### ISSUE THREAD

**Issue by gatm50** [hawkerm/monaco-editor-uwp#24]
The method SetPosition is missing:

```
       /**
         * Set the primary position of the cursor. This will remove any secondary cursors.
         * @param position New primary cursor's position
         */
        setPosition(position: IPosition): void;
```
I have added the method on my fork but I would like to share it
Do you accept contributions?

**Comment by hawkerm** [comment]
@gatm50 there are many functions I havent plumbed yet. :) I've been adding them as I need them in groups as I can.

I'll have to look at how to add contribution guidelines and such to ensure repo integrity.  It may get absorbed later, but open to figuring it out.  The more the merrier!

**Comment by hawkerm** [comment]
Added in v0.8.0-alpha
