### ISSUE TITLE
Snippet functionality breaks when updating monaco release to 0.15.6?

### ISSUE THREAD

**Issue by hansmbakker** [hawkerm/monaco-editor-uwp#25]
It seems that the `foreach` snippet (which was a suggestion in TestApp) does not work after updating Monaco to release 0.15.6 - see https://github.com/hansmbakker/monaco-editor-uwp/tree/update

It works when using release 0.13.1

**Comment by hawkerm** [comment]
Thanks @hansmbakker, I haven't updated the Monaco version yet as they made this breaking change in 15.0:

> `CompletionItemProvider.provideCompletionItems` and `CompletionItemProvider.resolveCompletionItem` have been modified to better reflect the API of VS Code. Both arguments and return type have changed.

The corresponding API surface in the wrapper code needs to be updated to match.  That starts [here](https://github.com/hawkerm/monaco-editor-uwp/blob/master/MonacoEditorComponent/MonacoEditor.html#L89).

**Comment by hansmbakker** [comment]
@hawkerm I created a pull request (https://github.com/hawkerm/monaco-editor-uwp/pull/26) and asked for feedback there. Shall we continue the conversation there?

**Comment by hansmbakker** [comment]
I can imagine you have other things to do as well, but could you maybe give some indication when you would have time to look at my PR?
If you don’t have time that’s also an answer, but then at least i know what to expect :)
