### ISSUE TITLE
Add IEditorOption copyWithSyntaxHighlighting

### ISSUE THREAD

**Issue by Swiftpaws** [hawkerm/monaco-editor-uwp#27]
Please add this editor setting

[Monaco.d.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/monaco.d.ts#L2928)

in this [class](https://github.com/hawkerm/monaco-editor-uwp/blob/d897922d53f9c95bfe7ff979d08a8e43fb23416d/MonacoEditorComponent/Monaco/Editor/IEditorOptions.cs#L17)

**Comment by hawkerm** [comment]
Thanks @Swiftpaws for the suggestion.  It may have been a new setting I've overlooked.  I need to find a solution to better generate some/all of the C# from the TypeScript definitions.  There's a general discussion about that in the #26 PR from @hansmbakker.  As you can imagine writing the wrapper by hand isn't ideal.

I'll make sure to do a pass before the next release to get this one in though (and any other straight-forward ones missed).  I'm not sure when the next release/update will be at this time yet.
