### ISSUE TITLE
Drag and drop support needed(UWP)

### ISSUE THREAD

**Issue by DmitryBorodiy** [hawkerm/monaco-editor-uwp#73]
Hello!
How I can implement drag & drop support in CodeEditor control?

Thank you!
Best wishes!

**Comment by hawkerm** [comment]
@DmitryBorodiy what are you trying to drag and drop? Like loading a file? You should just be able to intercept a drag event like any other control and then read the StorageFile and load it yourself at the app level.

It could be interesting as part of a sample, but not something I would think the control should necessarily handle on its own.
